@startuml

control "Job Monitor"
database "Scooter"
database "Monitor"

group Job monitor scooter location

'check scooter
"Job Monitor" -> "Scooter": Select all Scooters

activate "Job Monitor" #FFBBBB

activate "Scooter" #FFBBBB

"Scooter" --> "Job Monitor": Selected Scooters

deactivate "Scooter"


'insert scooter
"Job Monitor" -> "Monitor": Insert rented Scooters location

activate "Monitor" #FFBBBB

"Monitor" --> "Job Monitor": Inserted location

deactivate "Monitor"


"Job Monitor" --> "Job Monitor": Retrigger each 1 min.

deactivate "Job Monitor"

end

@enduml