@startuml

skinparam handwritten true
skinparam roundcorner 10
skinparam sequenceArrowThickness 3

actor "User"
entity "Scooter Service"
database "Scooter"
collections "Tracking Queue"

group Turning back a scooter

'user 
"User" -> "Scooter Service" : Post - Scooter ID

activate "User" #FFBBBB
activate "Scooter Service" #FFBBBB


'check scooter
"Scooter Service" -> "Scooter": Select Scooter

activate "Scooter" #FFBBBB

"Scooter" --> "Scooter Service": Selected Scooter

deactivate "Scooter"


'update scooter
"Scooter Service" -> "Scooter": Update Scooter (turn back)

activate "Scooter" #FFBBBB

'Request insert Tracking Queue
"Scooter" --> "Tracking Queue": Event Insert Tracking Async

activate "Tracking Queue"

"Scooter" --> "Scooter Service": Updated Scooter

deactivate "Scooter"


'Finish
"Scooter Service" --> "User": Sucessful Message
deactivate "Scooter Service"
deactivate "User"

deactivate "Tracking Queue"

end

@enduml