@startuml

skinparam handwritten true
skinparam roundcorner 10
skinparam sequenceArrowThickness 3

control "Job Tracking"
collections "Tracking Queue"

group Turning back a Scooter

'Request insert Tracking Queue
"Job Tracking" --> "Tracking Queue": Event Insert Tracking Async

activate "Job Tracking" #FFBBBB

activate "Tracking Queue"

"Job Tracking" --> "Job Tracking": Retrigger each 1 min.

'Finish
deactivate "Job Tracking"

deactivate "Tracking Queue"

end

@enduml