@startuml

skinparam handwritten true
skinparam roundcorner 10
skinparam sequenceArrowThickness 3

collections "Tracking Queue"
entity "Tracking Service"
database "Tracking"

group Tracking Event

'Tracking Queue 

loop every new queue item

activate "Tracking Queue"

"Tracking Queue" --> "Tracking Service" : Pop Update Scooter location

activate "Tracking Service" #FFBBBB

end


'insert tracking
"Tracking Service" -> "Tracking": Insert tracking location

activate "Tracking" #FFBBBB

"Tracking" --> "Tracking Service": Inserted tracking

deactivate "Tracking"

'Finish
deactivate "Tracking Service"
deactivate "Tracking Queue"

end

@enduml